-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION
--TABLE
select  * from countries;
select * from REGIONS;
select COUNTRY_NAME, REGION_NAME from COUNTRIES
    left join REGIONS
        on COUNTRIES.REGION_ID = REGIONS.REGION_ID;


-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
    select first_name,job_title
    from EMPLOYEES
        left join JOBS J
            on EMPLOYEES.JOB_ID = J.JOB_ID;
-- 3. FIND OUT DEPARTMENT_NAME AND CITY
select  DEPARTMENT_NAME, CITY
from DEPARTMENTS
    left join  LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;
-- 4. FIND OUT ALL CITIES  AND COUNTRY NAMES
select  CITY,COUNTRY_NAME
from LOCATIONS
    left join  COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID;

-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR
 --   DEPARTMENT ID 80 OR 40
select FIRST_NAME, LAST_NAME,d.DEPARTMENT_ID , DEPARTMENT_NAME
from EMPLOYEES
inner join DEPARTMENTS d
on EMPLOYEES.DEPARTMENT_ID = d.DEPARTMENT_ID
where d.DEPARTMENT_ID=80 or d.DEPARTMENT_ID=40 ;

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select * from COUNTRIES;
select * from LOCATIONS;
select CITY,COUNTRY_NAME, REGION_NAME
from LOCATIONS
inner join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
inner join REGIONS
on COUNTRIES.REGION_ID = REGIONS.REGION_ID;

-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
select  FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
from EMPLOYEES
    inner join JOBS
on EMPLOYEES.JOB_ID = JOBS.JOB_ID
  inner join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
inner join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;

-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY ,
--COUNTRY_NAME , REGION_NAME
select  FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY,COUNTRY_NAME,REGION_NAME
from EMPLOYEES
 inner join JOBS
 on EMPLOYEES.JOB_ID = JOBS.JOB_ID
inner join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
inner join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
inner join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
inner join REGIONS
on COUNTRIES.REGION_ID = REGIONS.REGION_ID;


--9. FIND OUR  EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL
--DEPARTMENTS
--  INCLUDING  WHERE DO NOT HAVE ANY EMPLOYEE.
--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT
--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT

--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS  DOES NOT HAVE ANY MATCHING EMPLOYEES
select FIRST_NAME,EMPLOYEES.DEPARTMENT_ID,department_name
from EMPLOYEES full join DEPARTMENTS
    on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
